### ISSUE TITLE
Medium.call

### ISSUE THREAD

**Issue by rochakagrawal** [njuljsong/wsjUnblock#9] opened 2017-10-21 07:58 UTC
Any chance of bypassing paywall for medium.com ??

**Comment by njuljsong** [comment] 2017-10-21 21:49
I have no plan to do that. Maybe someone else?

**Comment by rochakagrawal** [comment] 2017-10-21 23:41
Please could you do ? Not sure - who else has the knowledge to do so

**Comment by hotcap** [comment] 2017-10-24 05:33
@rochakagrawal I think you could add something like

```javascript
  "permissions": [
    // more lines here
    "https://*.medium.com/*",
    "http://*.medium.com/*",
    // more lines here
   ]
```

to `manifest.json` and

```javascript
var sites = {
	// more lines here
	medium: {
		js: [ "*://*.medium.com/_/fp/gen-js/main-base.bundle.*.js" ]
	},
	// more lines here
};
```

to `src/bg/background.js` and reloading the plugin.

But medium.com doesn't seem like much of a pest with the paywalls, and they also have a bunch of affiliate posts linking to other domains which may have their own army of custom paywalls for all I know. Good luck buddy

**Comment by allenleein** [comment] 2017-10-24 07:36
@hotcap I tried but it seems not working.

**Comment by hotcap** [comment] 2017-10-24 17:19
@allenleein Not sure. Post your `permissions` and `sites` entries as above and I might be able to figure it out - or you can check yourself to see if there are any JavaScript errors in the extension by going to your extensions and clicking the "background page" link on this plugin, and then, in the resulting dialog, going to the "Console" tab.

**Comment by rochakagrawal** [comment] 2017-10-24 23:14
@hotcap any working solutions pls that you have tested working.  Unfortunately solution above doesn't work and doesn't throw any error too

**Comment by hotcap** [comment] 2017-10-25 00:01
@rochakagrawal Not sure what the issue is on your end as it appeared to be working for me - maybe you can send me a URL to test on?

**Comment by rochakagrawal** [comment] 2017-10-29 12:54
Sure, try this URL
https://betterhumans.coach.me/how-to-stop-being-addicted-to-facebook-cb4c1138d63

**Comment by hotcap** [comment] 2017-10-29 23:26
@rochakagrawal unfortunately that's not a URL originating at medium.com, it looks to be some affiliated site - of which there seem to be a ton, and it would take a while to enumerate, fix, and test them all.

But the *really* bad news is, the paywall on this page is not some timer/asynchronous Javascript that hides content after the fact, it appears you're served up a preview right off the bat - so the paywall mechanism can't simply be disabled, which is more-or-less what wsjUnblock is designed to do. At this point you might as well feed them some credentials, which is possible to automate, but it's not something I have time to do and not really in the spirit of wsjUnblock's design anyway.

Sorry, no-can-do :-\

**Comment by njuljsong** [comment] 2018-01-29 01:27
Thanks @hotcap 

I close this one for the reason above.

**Closed by njuljsong** 2018-01-29 01:27 UTC
